//
// Created by Shubham on 20/06/18.
//

#ifndef PROJ_ANDROID_DEFINATIONS_H
#define PROJ_ANDROID_DEFINATIONS_H

#define NO_OF_CARS_IN_LEFT_SIDE 5
#define NO_OF_CARS_IN_RIGHT_SIDE 5

#define DISTANCE_BETWEEN_CARS 120

#define PLAYER_SPEED 20

#endif //PROJ_ANDROID_DEFINATIONS_H
